<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-26T00:30:07 IST" name="Default suite" finished-at="2022-03-26T00:30:14 IST" duration-ms="6930">
    <groups>
    </groups>
    <test started-at="2022-03-26T00:30:07 IST" name="Default test" finished-at="2022-03-26T00:30:14 IST" duration-ms="6930">
      <class name="testcases.SaucedemoLoginTest">
        <test-method is-config="true" signature="DataSetUP()[pri:0, instance:testcases.SaucedemoLoginTest@18d87d80]" started-at="2022-03-26T00:30:07 IST" name="DataSetUP" finished-at="2022-03-26T00:30:08 IST" duration-ms="325" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataSetUP -->
        <test-method is-config="true" signature="Setup(java.lang.reflect.Method)[pri:0, instance:testcases.SaucedemoLoginTest@18d87d80]" started-at="2022-03-26T00:30:08 IST" name="Setup" finished-at="2022-03-26T00:30:10 IST" duration-ms="2691" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.SaucedemoLoginTest.LoginFailureTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="LoginFailureTest()[pri:0, instance:testcases.SaucedemoLoginTest@18d87d80]" started-at="2022-03-26T00:30:10 IST" name="LoginFailureTest" finished-at="2022-03-26T00:30:11 IST" duration-ms="685" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Epic sadface: Username and password do not match any user in this service.] but found [Epic sadface: Username and password do not match any user in this service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password do not match any user in this service.] but found [Epic sadface: Username and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testcases.SaucedemoLoginTest.LoginFailureTest(SaucedemoLoginTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFailureTest -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases.SaucedemoLoginTest@18d87d80]" started-at="2022-03-26T00:30:11 IST" name="TearDown" finished-at="2022-03-26T00:30:11 IST" duration-ms="235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="Setup(java.lang.reflect.Method)[pri:0, instance:testcases.SaucedemoLoginTest@18d87d80]" started-at="2022-03-26T00:30:11 IST" name="Setup" finished-at="2022-03-26T00:30:13 IST" duration-ms="1501" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.SaucedemoLoginTest.LoginSuccessTest()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="LoginSuccessTest()[pri:0, instance:testcases.SaucedemoLoginTest@18d87d80]" started-at="2022-03-26T00:30:13 IST" name="LoginSuccessTest" finished-at="2022-03-26T00:30:13 IST" duration-ms="587" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginSuccessTest -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases.SaucedemoLoginTest@18d87d80]" started-at="2022-03-26T00:30:13 IST" name="TearDown" finished-at="2022-03-26T00:30:14 IST" duration-ms="231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="DataTearDown()[pri:0, instance:testcases.SaucedemoLoginTest@18d87d80]" started-at="2022-03-26T00:30:14 IST" name="DataTearDown" finished-at="2022-03-26T00:30:14 IST" duration-ms="588" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataTearDown -->
      </class> <!-- testcases.SaucedemoLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
